/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author Kurea
 */
public class individualDevelopmentPlan extends javax.swing.JFrame {
    
    private static final String url = "jdbc:mysql://localhost:3306/saad";
    private static final String username = "root";
    private static final String password = "$4Y my n4m3";
    
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form individualDevelopmentPlan
     */
    public individualDevelopmentPlan() {
        initComponents();
    }
    JFileChooser fileChooser = new JFileChooser();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_positionTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_deptHeadName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_employeeName = new javax.swing.JTextField();
        tf_positionTitle_head = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_supervisorName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_contactNumber_supervisor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_positionTitle_supervisor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_emailAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_contactNumber_head = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_contactNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_emailAddress_supervisor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_emailAddress_head = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cb_sg = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        longTermGoals = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        goalsPerformance = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        shortTermGoals = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tf_remarks = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        preview1 = new javax.swing.JButton();
        preview2 = new javax.swing.JButton();
        preview3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Individual Development Plan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setMinimumSize(new java.awt.Dimension(1680, 1020));
        jPanel2.setPreferredSize(new java.awt.Dimension(1680, 1020));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Position Title");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        tf_positionTitle.setToolTipText("45 characters max.");
        tf_positionTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_positionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_positionTitleActionPerformed(evt);
            }
        });
        jPanel2.add(tf_positionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 340, 37));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("<html>Institute/Department<br>Head's Name</html>");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, 122, 40));

        tf_deptHeadName.setToolTipText("150 characters max.");
        tf_deptHeadName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_deptHeadName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 50, 320, 37));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Employee's Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 20));

        tf_employeeName.setToolTipText("150 characters max.");
        tf_employeeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_employeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_employeeNameActionPerformed(evt);
            }
        });
        jPanel2.add(tf_employeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 340, 37));

        tf_positionTitle_head.setToolTipText("45 characters max.");
        tf_positionTitle_head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_positionTitle_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, 320, 37));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Position Title");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, 122, 20));

        tf_supervisorName.setToolTipText("150 characters max.");
        tf_supervisorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_supervisorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 360, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Supervisor's Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 122, 20));

        tf_contactNumber_supervisor.setToolTipText("11 digit phone number.");
        tf_contactNumber_supervisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_contactNumber_supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 360, 37));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Contact Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 122, 20));

        tf_positionTitle_supervisor.setToolTipText("45 characters max.");
        tf_positionTitle_supervisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_positionTitle_supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 360, 37));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Position Title");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 122, 20));

        tf_emailAddress.setToolTipText("150 characters max.");
        tf_emailAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 340, 37));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Email Address");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 122, 20));

        tf_contactNumber_head.setToolTipText("11 digit phone number.");
        tf_contactNumber_head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_contactNumber_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 150, 320, 37));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Contact Number");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 122, 20));

        tf_contactNumber.setToolTipText("11 digit phone number.");
        tf_contactNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_contactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 340, 37));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Contact Number");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 122, 20));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email Address");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 122, 20));

        tf_emailAddress_supervisor.setToolTipText("150 characters max.");
        tf_emailAddress_supervisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_emailAddress_supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 360, 37));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Email Address");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, 122, 20));

        tf_emailAddress_head.setToolTipText("150 characters max.");
        tf_emailAddress_head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tf_emailAddress_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 200, 320, 37));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Salary Grade");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, 30));

        cb_sg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SG 1", "SG 2", "SG 3", "SG 4", "SG 5", "SG 6", "SG 7", "SG 8", "SG 9", "SG 10", "SG 11", "SG 12", "SG 13", "SG 14", "SG 15", "SG 16", "SG 17", "SG 18", "SG 19", "SG 20", "SG 21", "SG 22", "SG 23", "SG 24", "SG 25", "SG 26", "SG 27", "SG 28", "SG 29", "SG 30", "SG 31", "SG 32", "SG 33" }));
        cb_sg.setSelectedIndex(-1);
        cb_sg.setToolTipText("select salary grade");
        cb_sg.setBorder(null);
        jPanel2.add(cb_sg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 340, 40));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Short-term career goals (2-3 years)");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 260, 30));

        longTermGoals.setColumns(20);
        longTermGoals.setRows(5);
        longTermGoals.setToolTipText("250 characters max.");
        longTermGoals.setWrapStyleWord(true);
        longTermGoals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(longTermGoals);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 370, 470, 140));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html>Goals for at least \"Very Satisfactory\"<br> or \"Outstanding\" Performance in Present Position</html>");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 270, 50));

        goalsPerformance.setColumns(20);
        goalsPerformance.setRows(5);
        goalsPerformance.setToolTipText("250 characters max.");
        goalsPerformance.setWrapStyleWord(true);
        goalsPerformance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(goalsPerformance);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 470, 140));

        shortTermGoals.setColumns(20);
        shortTermGoals.setRows(5);
        shortTermGoals.setToolTipText("250 characters max.");
        shortTermGoals.setWrapStyleWord(true);
        shortTermGoals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(shortTermGoals);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 470, 140));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Long-term career goals (3+ years)");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 230, 30));

        jLabel17.setText("Remarks:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 730, 90, 30));

        tf_remarks.setColumns(20);
        tf_remarks.setLineWrap(true);
        tf_remarks.setRows(5);
        tf_remarks.setToolTipText("");
        tf_remarks.setWrapStyleWord(true);
        tf_remarks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(tf_remarks);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 760, 530, 110));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Developmental Objectives", "L&D Methodologies/Interventions", "Proposed Dates", "Estimated Costs FY", "Date Completed"
            }
        ));
        jTable1.setToolTipText("define your 5 objectives");
        jTable1.setCellSelectionEnabled(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setName(""); // NOI18N
        jTable1.setOpaque(false);
        jTable1.setSelectionBackground(new java.awt.Color(243, 243, 243));
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane9.setViewportView(jTable1);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 1180, 170));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Specific Target Training to be Attended", "Timeframe"
            }
        ));
        jTable2.setToolTipText("provide 2 trainings to attend");
        jTable2.setFillsViewportHeight(true);
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setOpaque(false);
        jTable2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane10.setViewportView(jTable2);

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, 530, 130));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Employee Signature:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 540, 140, 30));

        jButton1.setText("Upload File...");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 540, 120, 30));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField13.setOpaque(true);
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 650, 170, -1));

        jLabel1.setText("file chosen:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 650, -1, 20));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Supervisor's Signature:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 680, 140, 30));

        jButton2.setText("Upload File...");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 680, 120, 30));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField14.setOpaque(true);
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 790, 170, -1));

        jLabel4.setText("file chosen:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 790, -1, 20));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dept. Head's Signature:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 830, 140, 30));

        jButton3.setText("Upload File...");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 830, 120, 30));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField15.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField15.setOpaque(true);
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 940, 170, -1));

        jLabel5.setText("file chosen:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 940, -1, 20));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setText("Submit");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 890, 100, 40));

        jButton5.setText("Print Form...");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 890, 110, 40));

        jButton6.setText("Export to CSV...");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 890, 100, 40));

        preview1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        preview1.setContentAreaFilled(false);
        preview1.setFocusPainted(false);
        preview1.setFocusable(false);
        preview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preview1ActionPerformed(evt);
            }
        });
        jPanel2.add(preview1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 580, 250, 60));

        preview2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        preview2.setContentAreaFilled(false);
        preview2.setFocusPainted(false);
        jPanel2.add(preview2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 720, 250, 60));

        preview3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        preview3.setContentAreaFilled(false);
        jPanel2.add(preview3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 870, 250, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 1020));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_positionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_positionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_positionTitleActionPerformed

    private void tf_employeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_employeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_employeeNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
        --upload file--
        */
        int res = fileChooser.showOpenDialog(null);

        if(res == JFileChooser.APPROVE_OPTION)
        {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            jTextField13.setText(file.toString());

            // Set icon for preview1 to the chosen file
            try {
                BufferedImage image = ImageIO.read(file);
                ImageIcon icon = new ImageIcon(image);
                Image scaledImage = icon.getImage().getScaledInstance(250, 60, java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                preview1.setIcon(scaledIcon);
            } catch (IOException e) {
                System.err.println("Error reading image file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        /*
        --upload file--
        */
        int res = fileChooser.showOpenDialog(null);

        if(res == JFileChooser.APPROVE_OPTION)
        {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            jTextField14.setText(file.toString());

            // Set icon for preview1 to the chosen file
            try {
                BufferedImage image = ImageIO.read(file);
                ImageIcon icon = new ImageIcon(image);
                Image scaledImage = icon.getImage().getScaledInstance(250, 60, java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                preview2.setIcon(scaledIcon);
            } catch (IOException e) {
                System.err.println("Error reading image file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        /*
        --upload file--
        */
        int res = fileChooser.showOpenDialog(null);

        if(res == JFileChooser.APPROVE_OPTION)
        {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            jTextField15.setText(file.toString());

            // Set icon for preview1 to the chosen file
            try {
                BufferedImage image = ImageIO.read(file);
                ImageIcon icon = new ImageIcon(image);
                Image scaledImage = icon.getImage().getScaledInstance(250, 60, java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                preview3.setIcon(scaledIcon);
            } catch (IOException e) {
                System.err.println("Error reading image file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        /*
            print form
        */
        PrinterJob pJob = PrinterJob.getPrinterJob();
        pJob.setJobName("Print form");

        PageFormat pf = pJob.defaultPage();
        pf.setPaper(new Paper());
        pf.getPaper().setImageableArea(0, 0, 612, 1008); // Legal size paper
        pf.getPaper().setSize(612, 1008); // Legal size paper

        pJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics pg, PageFormat pf, int pageNum){

                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate((int) pf.getImageableX(), (int) pf.getImageableY());

                // Calculate the scale factor to fit the panel to the paper
                double scaleFactor = Math.min(pf.getImageableWidth() / jPanel2.getWidth(), pf.getImageableHeight() / jPanel2.getHeight());

                // Apply the scale factor
                g2.scale(scaleFactor, scaleFactor);

                jPanel2.printAll(g2);
                return Printable.PAGE_EXISTS;
            }
        });

        boolean ok = pJob.printDialog();
        if(ok)
        {
            try{
                pJob.print();
            } catch (PrinterException ex) {
                Logger.getLogger(individualDevelopmentPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // variables
        String employeeName = tf_employeeName.getText();
        String supervisorName = tf_supervisorName.getText();
        String deptHeadName = tf_deptHeadName.getText();
        
        String employeePosition = tf_positionTitle.getText();
        String supervisorPosition = tf_positionTitle_supervisor.getText();
        String headPosition = tf_positionTitle_head.getText();
        
        String salaryGrade = cb_sg.getSelectedItem().toString();
        String employeeContact = tf_contactNumber.getText();
        String supervisorContact = tf_contactNumber_supervisor.getText();
        String headContact = tf_contactNumber_head.getText();
        
        String employeeEmail = tf_emailAddress.getText();
        String supervisorEmail = tf_emailAddress_supervisor.getText();
        String headEmail = tf_emailAddress_head.getText();
        
        String performanceGoals = goalsPerformance.getText();
        String shortTerm = shortTermGoals.getText();
        String longTerm = longTermGoals.getText();
        String remarks = tf_remarks.getText();
        
        // table data
        TableModel model = jTable1.getModel();
        
        // first row
        
        /*
        // second row
        String devtObj1 = (String) model.getValueAt(1, 0);
        String methods1 = (String) model.getValueAt(1, 1);
        String date1 = (String) model.getValueAt(1, 2);
        String estCost1 = (String) model.getValueAt(1, 3);
        String dateCompleted1 = (String) model.getValueAt(1, 4);
        
        // third row
        String devtObj2 = (String) model.getValueAt(2, 0);
        String methods2 = (String) model.getValueAt(2, 1);
        String date2 = (String) model.getValueAt(2, 2);
        String estCost2 = (String) model.getValueAt(2, 3);
        String dateCompleted2 = (String) model.getValueAt(2, 4);
        
        // fourth row
        String devtObj3 = (String) model.getValueAt(3, 0);
        String methods3 = (String) model.getValueAt(3, 1);
        String date3 = (String) model.getValueAt(3, 2);
        String estCost3 = (String) model.getValueAt(3, 3);
        String dateCompleted3 = (String) model.getValueAt(3, 4);
        
        // fifth row
        String devtObj4 = (String) model.getValueAt(4, 0);
        String methods4 = (String) model.getValueAt(4, 1);
        String date4 = (String) model.getValueAt(4, 2);
        String estCost4 = (String) model.getValueAt(4, 3);
        String dateCompleted4 = (String) model.getValueAt(4, 4);
        
        */
        
        
        /**
         * saving data input to database
         */
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("individualDevelopmentPlan.jButton4ActionPerformed()");
            // basic information
            conn = DriverManager.getConnection(url,username,password);
            pst = conn.prepareStatement("INSERT INTO `saad`.`idp_basic_info` (`employee_name`,`supervisor_name`,`dept_head_name`,`position_title`,`salary_grade`,`contact_number`,`email_address`,`position_title_supervisor`,`position_title_head`,`email_address_supervisor`,`email_address_head`,`contact_number_supervisor`,`contact_number_head`,`remarks`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, employeeName);
            pst.setString(2, supervisorName);
            pst.setString(3, deptHeadName);
            pst.setString(4, employeePosition);
            pst.setString(5, salaryGrade);
            pst.setString(6, employeeContact);
            pst.setString(7, employeeEmail);
            pst.setString(8, supervisorPosition);
            pst.setString(9, headPosition);
            pst.setString(10, supervisorEmail);
            pst.setString(11, headEmail);
            pst.setString(12, supervisorContact);
            pst.setString(13, headContact);
            pst.setString(14, remarks);
            pst.executeUpdate();
            
            // goals
            pst = conn.prepareStatement("INSERT INTO `saad`.`idp_goals` (`goals_present_position`, `goals_short_term`, `goals_long_term`, `employee_name`) VALUES('"+ performanceGoals +"', '"+ shortTerm +"', '"+ longTerm +"', '"+ employeeName +"') ");
            pst.executeUpdate();
            System.out.println("goals");
            
            // objectives
            pst = conn.prepareStatement("INSERT INTO `saad`.`idp_devt_objectives` (`developmental_obj`, `methods`, `proposed_date`, `estimated_costs`, `date_completed`) VALUES (?,?,?,?,?) ");
            System.out.println("individualDevelopmentPlan.objectives");
            for (int row = 0; row < model.getRowCount(); row++) {
                pst.setString(1, (String) model.getValueAt(row, 0));
                pst.setString(2, (String) model.getValueAt(row, 1));
                pst.setString(3, (String) model.getValueAt(row, 2));
                pst.setString(4, (String) model.getValueAt(row, 3));
                pst.setString(5, (String) model.getValueAt(row, 4));
                pst.addBatch();
            }
            pst.executeBatch();
            
            // training
            TableModel model_1 = jTable2.getModel();
            System.out.println("individualDevelopmentPlan.training");
            pst = conn.prepareStatement("INSERT INTO `saad`.`idp_training` (`target_training`, `timeframe`) VALUES (?,?)");
            for (int row = 0; row < model_1.getRowCount(); row++) {
                pst.setString(1, (String) model_1.getValueAt(row, 0));
                pst.setString(2, (String) model_1.getValueAt(row, 1));
                pst.addBatch();
            }
            pst.executeBatch();
            JOptionPane.showMessageDialog(null, "input updated to database.", "success", JOptionPane.INFORMATION_MESSAGE);
            
            
            // Retrieve file data - upload to db
            String filePath1 = jTextField13.getText(); // Get the file path from jTextField13
            String filePath2 = jTextField14.getText(); // Get the file path from jTextField14
            String filePath3 = jTextField15.getText(); // Get the file path from jTextField15

            try (FileInputStream fis1 = new FileInputStream(filePath1);
                 FileInputStream fis2 = new FileInputStream(filePath2);
                 FileInputStream fis3 = new FileInputStream(filePath3)) {

                pst = conn.prepareStatement("INSERT INTO `saad`.`idp_signatures` (`employee_name`, `supervisor_name`, `dept_head_name`, `employee_signature`, `supervisor_signature`, `dept_head_signature`) VALUES(?,?,?,?,?,?)");
                pst.setString(1, employeeName);
                pst.setString(2, supervisorName);
                pst.setString(3, deptHeadName);
                pst.setBinaryStream(4, fis1, fis1.available()); // Set employee signature
                pst.setBinaryStream(5, fis2, fis2.available()); // Set supervisor signature
                pst.setBinaryStream(6, fis3, fis3.available()); // Set dept head signature

                pst.executeUpdate();

            } catch (IOException | SQLException e) {
                e.printStackTrace();
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } finally {
            // Close resources
            if (pst != null) try { pst.close(); } catch (Exception e) { /* ignored */ }
            if (conn != null) try { conn.close(); } catch (Exception e) { /* ignored */ }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        // Collect input data from all JPanel components
        List<String> data = new ArrayList<>();

        for (int i = 0; i < jPanel2.getComponentCount(); i++) {
            Component component = jPanel2.getComponent(i);
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                data.add(textField.getText());
            } else if (component instanceof JTextArea) {
                JTextArea textArea = (JTextArea) component;
                data.add(textArea.getText());
            } else if (component instanceof JComboBox) {
                JComboBox comboBox = (JComboBox) component;
                data.add((String) comboBox.getSelectedItem());
            } else if (component instanceof JTable) {
                JTable table = (JTable) component;
                TableModel tableModel = table.getModel();
                int rowCount = tableModel.getRowCount();
                for (int j = 0; j < rowCount; j++) {
                    StringBuilder rowData = new StringBuilder();
                    for (int k = 0; k < tableModel.getColumnCount(); k++) {
                        rowData.append(tableModel.getValueAt(j, k)).append(",");
                    }
                    data.add(rowData.toString());
                }
            }
        }

        // Write data to CSV file
        String csvFile = "export.csv";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(csvFile))) {
            for (String datum : data) {
                writer.write(datum + ",");
            }
            writer.newLine();
        } catch (IOException e) {
            System.err.println("Error writing to CSV file: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void preview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preview1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preview1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(individualDevelopmentPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(individualDevelopmentPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(individualDevelopmentPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(individualDevelopmentPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new individualDevelopmentPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_sg;
    private javax.swing.JTextArea goalsPerformance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextArea longTermGoals;
    private javax.swing.JButton preview1;
    private javax.swing.JButton preview2;
    private javax.swing.JButton preview3;
    private javax.swing.JTextArea shortTermGoals;
    private javax.swing.JTextField tf_contactNumber;
    private javax.swing.JTextField tf_contactNumber_head;
    private javax.swing.JTextField tf_contactNumber_supervisor;
    private javax.swing.JTextField tf_deptHeadName;
    private javax.swing.JTextField tf_emailAddress;
    private javax.swing.JTextField tf_emailAddress_head;
    private javax.swing.JTextField tf_emailAddress_supervisor;
    private javax.swing.JTextField tf_employeeName;
    private javax.swing.JTextField tf_positionTitle;
    private javax.swing.JTextField tf_positionTitle_head;
    private javax.swing.JTextField tf_positionTitle_supervisor;
    private javax.swing.JTextArea tf_remarks;
    private javax.swing.JTextField tf_supervisorName;
    // End of variables declaration//GEN-END:variables
}
